# Generated by Django 2.2.4 on 2019-08-26 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='population',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Roompop', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('name', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_type', models.CharField(choices=[('Single', 'Singles Rooms'), ('Double', 'Doubles Rooms'), ('Triple', 'Triples Rooms'), ('Quadruple', 'Quadruples Rooms')], default='s', help_text='select room type', max_length=20)),
                ('price', models.IntegerField(choices=[(0, '-----'), (20, '€20 / day'), (30, '€30 / day'), (40, '€40 / day'), (50, '€50 / day')], default=0, help_text='add room price')),
                ('Room_status', models.CharField(blank=True, choices=[('aval', 'Avalible'), ('cnfm', 'Confirmed'), ('chki', 'Checked In'), ('chko', 'Checked Out')], default='aval', help_text='select Room status', max_length=4, null=True)),
                ('Reserved_from', models.DateField(blank=True, null=True)),
                ('Reserved_to', models.DateField(blank=True, null=True)),
                ('Room_number', models.IntegerField()),
                ('Descrition', models.TextField(blank=True, help_text='a brief description of the hotel room', max_length=200, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
                ('Reservation_ticket', models.CharField(blank=True, max_length=20, null=True)),
                ('Room_pop', models.ManyToManyField(blank=True, to='searchengine.population')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='searchengine.Profile')),
            ],
            options={
                'permissions': (('can_validate_ticket', 'can validate ticket'),),
            },
        ),
    ]
