# Generated by Django 2.2.4 on 2019-08-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchengine', '0003_hotel_model_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel_model',
            name='Room_status',
            field=models.CharField(blank=True, choices=[('Avalible', 'Avalible'), ('Confirmed', 'Confirmed'), ('Checked_In', 'Checked In'), ('Checked_Out', 'Checked Out')], default='aval', help_text='select Room status', max_length=20, null=True),
        ),
    ]
