# Generated by Django 2.2.4 on 2019-08-27 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchengine', '0005_auto_20190826_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel_model',
            name='thumbnail',
            field=models.ImageField(default='test', upload_to=''),
            preserve_default=False,
        ),
    ]
