# Generated by Django 2.2.4 on 2019-08-27 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchengine', '0007_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
