# Generated by Django 2.2.4 on 2019-08-27 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchengine', '0008_auto_20190827_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel_model',
            name='Reservation_ticket',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
