# Generated by Django 2.2.4 on 2019-08-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchengine', '0009_auto_20190827_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel_model',
            name='Room_status',
            field=models.CharField(blank=True, choices=[('Avalible', 'Avalible'), ('Confirmed', 'Confirmed'), ('Checked_In', 'Checked In'), ('Checked_Out', 'Checked Out')], default='Avalible', help_text='select Room status', max_length=20, null=True),
        ),
    ]
