# Generated by Django 2.2.4 on 2019-10-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchengine', '0011_auto_20190830_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel_model',
            name='Room_pop',
            field=models.ManyToManyField(blank=True, default='1', to='searchengine.Population'),
        ),
    ]
